name: Firefly Pico
version: "0.1.0"
slug: firefly-pico
description: Mobile-first web UI for Firefly III
url: https://github.com/cioraneanu/firefly-pico
arch:
  - amd64
  - aarch64
startup: services
boot: auto
panel: false
ports:
  3000/tcp: 8070
options:
  FIREFLY_III_URL: "http://your-firefly-url:8080"
  FIREFLY_III_PAT: "PASTE_YOUR_PAT_HERE"
schema:
  FIREFLY_III_URL: str
  FIREFLY_III_PAT: str
environment:
  FIREFLY_III_URL: "http://your-firefly-url:8080"
  FIREFLY_III_PAT: "PASTE_YOUR_PAT_HERE"
image: "ghcr.io/cioraneanu/firefly-pico"
