name: Firefly Pico
version: "0.1.0"
slug: firefly-pico
description: Mobile-first web UI for Firefly III
url: https://github.com/cioraneanu/firefly-pico
arch:
  - amd64
  - aarch64
startup: services
boot: auto
ingress: true
panel_admin: false
panel_icon: "mdi:piggy-bank"
icon: "icon.png"
ports:
  3000/tcp: 8070
options:
  FIREFLY_III_URL: "http://<addon-id>-firefly-iii:8080"
  FIREFLY_III_PAT: "PASTE_YOUR_PAT_HERE"
schema:
  FIREFLY_III_URL: str
  FIREFLY_III_PAT: str
environment:
  FIREFLY_URL: "{{ FIREFLY_URL }}"
  FIREFLY_TOKEN: "{{ FIREFLY_TOKEN }}"
